name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Check
        run: uv run ruff check
      - name: Format
        run: uv run ruff format --check
  deploy:
    name: Deploy
    needs: [lint]
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    environment:
      name: deploy
      url: ${{ steps.deploy.outputs.api_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::390960605471:role/stac-fastapi-geoparquet-examples-deploy
          role-session-name: stac-fastapi-geoparquet-examples-deploy
          aws-region: us-west-2
      - uses: actions/setup-node@v2
        with:
          node-version: 22
      - uses: astral-sh/setup-uv@v3
      - name: Install npm dependencies
        run: npm install
      - name: CDK Deploy
        id: deploy
        run: |
          uv run npm run cdk -- deploy --require-approval never --all
          API_URL=$(aws cloudformation describe-stacks --stack-name stac-fastapi-geoparquet-examples --query 'Stacks[0].Outputs[?OutputKey==`ApiURL`].OutputValue' --output text)
          echo "::notice title=API URL::${API_URL}"
          echo api_url=$API_URL >> $GITHUB_OUTPUT
